apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer-service
spec:
  selector:
    app.kubernetes.io/component: producer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.producer.service.port }}
      targetPort: {{ .Values.producer.containerPort }}
