server:
  port: 8080
spring:
  application:
    name: producer
  kafka:
    # use the docker-compose service name and internal listener port so containers can reach the broker
    bootstrap-servers: broker:9092
    producer:
      acks: all     # tels to kafka that don’t acknowledge my write until the message is safely replicated
      retries: 3    # set to zero (0) for at most one delivery semantic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true    # No duplicate messages per partition, even with retries
kafka:
  topics:
    payment-topic: payment-events
