apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-deployment
  labels:
    app: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: producer-service
          image: arunasilva/consumer-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/payment-db?replicaSet=rs0