apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service-deployment
  labels:
    app: producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: arunasilva/producer-service:1.0
          ports:
            - containerPort: 8080