apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-ui
spec:
  replicas: {{ .Values.kafkaUi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kafka-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUi.image.repository }}:{{ .Values.kafkaUi.image.tag }}"
          ports:
            - containerPort: {{ .Values.kafkaUi.service.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "{{ .Values.kafkaUi.kafka.name }}"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ .Values.kafkaUi.kafka.bootstrapServers }}"