apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-consumer
  labels:
    {{ include "payment-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: consumer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: consumer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: consumer-service
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          ports:
            - containerPort: {{ .Values.consumer.containerPort }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "{{ .Values.consumer.env.SPRING_DATA_MONGODB_URI }}"